const COUNTRY_CODES = [
  { code: '+971', country: 'AE', name: 'UAE', flag: '\u{1F1E6}\u{1F1EA}' },
  { code: '+91', country: 'IN', name: 'India', flag: '\u{1F1EE}\u{1F1F3}' },
  { code: '+966', country: 'SA', name: 'Saudi Arabia', flag: '\u{1F1F8}\u{1F1E6}' },
  { code: '+968', country: 'OM', name: 'Oman', flag: '\u{1F1F4}\u{1F1F2}' },
  { code: '+973', country: 'BH', name: 'Bahrain', flag: '\u{1F1E7}\u{1F1ED}' },
  { code: '+974', country: 'QA', name: 'Qatar', flag: '\u{1F1F6}\u{1F1E6}' },
  { code: '+965', country: 'KW', name: 'Kuwait', flag: '\u{1F1F0}\u{1F1FC}' },
  { code: '+44', country: 'GB', name: 'UK', flag: '\u{1F1EC}\u{1F1E7}' },
  { code: '+1', country: 'US', name: 'USA', flag: '\u{1F1FA}\u{1F1F8}' },
  { code: '+92', country: 'PK', name: 'Pakistan', flag: '\u{1F1F5}\u{1F1F0}' },
  { code: '+94', country: 'LK', name: 'Sri Lanka', flag: '\u{1F1F1}\u{1F1F0}' },
  { code: '+880', country: 'BD', name: 'Bangladesh', flag: '\u{1F1E7}\u{1F1E9}' },
  { code: '+977', country: 'NP', name: 'Nepal', flag: '\u{1F1F3}\u{1F1F5}' },
  { code: '+63', country: 'PH', name: 'Philippines', flag: '\u{1F1F5}\u{1F1ED}' },
  { code: '+86', country: 'CN', name: 'China', flag: '\u{1F1E8}\u{1F1F3}' },
  { code: '+81', country: 'JP', name: 'Japan', flag: '\u{1F1EF}\u{1F1F5}' },
  { code: '+82', country: 'KR', name: 'South Korea', flag: '\u{1F1F0}\u{1F1F7}' },
  { code: '+65', country: 'SG', name: 'Singapore', flag: '\u{1F1F8}\u{1F1EC}' },
  { code: '+60', country: 'MY', name: 'Malaysia', flag: '\u{1F1F2}\u{1F1FE}' },
  { code: '+62', country: 'ID', name: 'Indonesia', flag: '\u{1F1EE}\u{1F1E9}' },
  { code: '+66', country: 'TH', name: 'Thailand', flag: '\u{1F1F9}\u{1F1ED}' },
  { code: '+90', country: 'TR', name: 'Turkey', flag: '\u{1F1F9}\u{1F1F7}' },
  { code: '+20', country: 'EG', name: 'Egypt', flag: '\u{1F1EA}\u{1F1EC}' },
  { code: '+27', country: 'ZA', name: 'South Africa', flag: '\u{1F1FF}\u{1F1E6}' },
  { code: '+234', country: 'NG', name: 'Nigeria', flag: '\u{1F1F3}\u{1F1EC}' },
  { code: '+254', country: 'KE', name: 'Kenya', flag: '\u{1F1F0}\u{1F1EA}' },
  { code: '+49', country: 'DE', name: 'Germany', flag: '\u{1F1E9}\u{1F1EA}' },
  { code: '+33', country: 'FR', name: 'France', flag: '\u{1F1EB}\u{1F1F7}' },
  { code: '+39', country: 'IT', name: 'Italy', flag: '\u{1F1EE}\u{1F1F9}' },
  { code: '+34', country: 'ES', name: 'Spain', flag: '\u{1F1EA}\u{1F1F8}' },
  { code: '+31', country: 'NL', name: 'Netherlands', flag: '\u{1F1F3}\u{1F1F1}' },
  { code: '+61', country: 'AU', name: 'Australia', flag: '\u{1F1E6}\u{1F1FA}' },
  { code: '+64', country: 'NZ', name: 'New Zealand', flag: '\u{1F1F3}\u{1F1FF}' },
  { code: '+55', country: 'BR', name: 'Brazil', flag: '\u{1F1E7}\u{1F1F7}' },
  { code: '+52', country: 'MX', name: 'Mexico', flag: '\u{1F1F2}\u{1F1FD}' },
  { code: '+7', country: 'RU', name: 'Russia', flag: '\u{1F1F7}\u{1F1FA}' },
];

export default COUNTRY_CODES;
